fix: perf: generate function with transaction #20

diff --git a/perf/perf b/perf/perf
--- a/perf/perf
+++ b/perf/perf
@@ -1,27 +1,34 @@
 #! /bin/sh
 
 while [ $# -gt 0 ]; do
-  case "$1" in
-    --verbose)
-      verbose=1
-      ;;
-    --verbose=*)
-      verbose="${1#*=}"
-      ;;
-    --createdb)
-      createdb=1
-      ;;
-    --createdb=*)
-      createdb="${1#*=}"
-      ;;
-    *)
-      printf "***************************\n"
-      printf "* Error: Invalid argument.*\n"
-      printf "***************************\n"
-      exit 1
-  esac
-  shift
+    case "$1" in
+        --verbose)
+            verbose=2
+            ;;
+        --verbose=*)
+            verbose="${1#*=}"
+            ;;
+        --createdb)
+            createdb=1
+            ;;
+        --createdb=*)
+            createdb="${1#*=}"
+            ;;
+        *)
+            printf "***************************\n"
+            printf "* Error: Invalid argument.*\n"
+            printf "***************************\n"
+            exit 1
+    esac
+    shift
 done
+
+# --verbose=1 by default
+export verbose=${verbose:-1}
+
+if [ "$verbose" = 0 ] || [ "$verbose" = 1 ] ; then
+    exec &>/dev/null
+fi
 
 directory=$(dirname $0)
 
@@ -37,7 +44,7 @@ export OTHER_DATABASE=${OTHER_DATABASE:-postgres}
 export NUMBER_OF_PATIENTS=${NUMBER_OF_PATIENTS:-1000}
 export RAND_SEED=${RAND_SEED:-0.21}
 
-if [ "$verbose" = 2 ] ; then
+if [ "$verbose" = 3 ] ; then
     echo "PGHOST=$PGHOST"
     echo "PGDATABASE=$PGDATABASE"
     echo "PGPORT=$PGPORT"
@@ -53,48 +60,52 @@ fi
 
 if [ "$createdb" = 1 ] ; then
     if [ "$dropdb" = 1 ] ; then
-        ([ "$verbose" = 1 ] || [ "$verbose" = 2 ]) && \
+        ([ "$verbose" = 2 ] || [ "$verbose" = 3 ]) && \
             echo Drop $PGDATABASE database.
         read -r -d '' sql << EOF
 DROP DATABASE IF EXISTS $PGDATABASE;
 EOF
-        psql $OTHER_DATABASE --command="$sql" > /dev/null || exit 1
+        psql $OTHER_DATABASE --command="$sql" || exit 1
     fi
 
-    ([ "$verbose" = 1 ] || [ "$verbose" = 2 ]) && \
+    ([ "$verbose" = 2 ] || [ "$verbose" = 3 ]) && \
         echo Crate $PGDATABASE database.
     read -r -d '' sql << EOF
 CREATE DATABASE $PGDATABASE WITH OWNER $PGUSER ENCODING = 'UTF8';
 EOF
-    psql $OTHER_DATABASE --command="$sql" > /dev/null || exit 1
+    psql $OTHER_DATABASE --command="$sql" || exit 1
 
-    ([ "$verbose" = 1 ] || [ "$verbose" = 2 ]) && \
+    ([ "$verbose" = 2 ] || [ "$verbose" = 3 ]) && \
         echo Install Fhirbase into $PGDATABASE database.
-    psql --file="$directory"/../tmp/build.sql > /dev/null || exit 1
+    psql --file="$directory"/../tmp/build.sql || exit 1
 else
-    ([ "$verbose" = 1 ] || [ "$verbose" = 2 ]) && \
+    ([ "$verbose" = 2 ] || [ "$verbose" = 3 ]) && \
         echo Assume that database $PGDATABASE.$PG_SCHEMA \
              contains installed Fhirbase.
 fi
 
-([ "$verbose" = 1 ] || [ "$verbose" = 2 ]) && \
+([ "$verbose" = 2 ] || [ "$verbose" = 3 ]) && \
     echo Load temporary tables into $PGDATABASE.$PG_SCHEMA \
          from "$directory"/data.
-psql --file="$directory"/load.sql > /dev/null || exit 1
+psql --file="$directory"/load.sql || exit 1
 
 read -r -d '' sql << EOF
 SET plv8.start_proc = 'plv8_init';
 SELECT fhir_create_storage('{"resourceType": "Organization"}'::json);
 EOF
-psql --command="$sql" > /dev/null || exit 1
+psql --command="$sql" || exit 1
 
-([ "$verbose" = 1 ] || [ "$verbose" = 2 ]) && \
+([ "$verbose" = 2 ] || [ "$verbose" = 3 ]) && \
     echo Create generation functions in $PGDATABASE.$PG_SCHEMA.
-psql --file="$directory"/generate.sql > /dev/null || exit 1
+psql --file="$directory"/generate.sql || exit 1
 
-([ "$verbose" = 1 ] || [ "$verbose" = 2 ]) && echo Run performance tests.
+if [ "$verbose" != 0 ] ; then
+    exec &> /dev/tty
+fi
+
+([ "$verbose" = 2 ] || [ "$verbose" = 3 ]) && echo Run performance tests.
 read -r -d '' sql << EOF
 SET plv8.start_proc = 'plv8_init';
-SELECT generate(1, 0.28);
+SELECT generate($NUMBER_OF_PATIENTS, $RAND_SEED);
 EOF
-psql --command="$sql" > /dev/null || exit 1
+psql --command="$sql" || exit 1
